Add Course Info Card to the project
ekseverinets/react-app pull request #3
Opened 2023-02-22 03:11 UTC by ekseverinets

2023-02-25 10:09 UTC, stepan-lagunovsky requested changes

2023-02-25 10:09 UTC, stepan-lagunovsky commented on src/components/Root/RootComponent.tsx
> +	const [name, setName] = useState<string>('');
Please combine this two states into one like in the book.
In such case we separate our global state into 3 categories let's say and also avoid so callse 'prop drilling'.
Like in header component.

```
const [courses ...
const [authors ...
const [user ...
```
```
interface IUser {
  isAuth: boolean;
  name: string;
  email: string;
  token: string;
}
const [user, setUser] = useState<IUser>()
```
And then pass user. But not name, age, surname or whatever separately.

2023-02-25 14:27 UTC, YauheniyaSeviarynets commented on src/components/Header/Header.tsx
> +							className={({ isActive }) =>
ClassName is not a boolean attribute, so I can not pass 'false' to it, that's why I use 'undefined' here

2023-02-26 10:15 UTC, stepan-lagunovsky commented on src/components/Header/Header.tsx
> +							className={({ isActive }) =>
Definitely, nice catch!

2023-02-26 11:24 UTC, stepan-lagunovsky requested changes

2023-02-26 11:24 UTC, stepan-lagunovsky commented on src/components/Courses/components/CourseCard/CourseCard.tsx
> +// export interface IAuthors {
Remove commented line please.

2023-02-26 11:24 UTC, stepan-lagunovsky commented on src/components/Courses/components/CourseCard/CourseCard.tsx
> +export const CourseCard = ({
Please start with a comment at `RootComponent` about `models.ts`

And create `interface ICourseCardProps {}`.
Think how we can do this.

In TypeScript we can extend interfaces. Please google  this. 
So our `interface ICourseCardProps` should extend some interface which you already have in `models.ts` (Read the comment in RootComponent), and have some field with a type which you have in `models.ts` as well.

2023-02-26 11:24 UTC, stepan-lagunovsky commented on src/components/CourseInfo/CourseInfo.tsx
> +// interface CoursesProps {
Please start with a comment at `RootComponent` about `models.ts`
And then create `CourseInfoProps` instead of this comment.

2023-02-26 11:24 UTC, stepan-lagunovsky commented on src/components/Courses/Courses.tsx
> +// interface CoursesProps {
Please start with a comment at `RootComponent` about `models.ts`

Then change this comment into real `CoursesProps` using interfaces from `models.ts` and apply to Courses component.

2023-02-26 11:24 UTC, stepan-lagunovsky commented on src/components/CourseInfo/CourseInfo.tsx
> +// import { ICourse } from '../Courses/components/CourseCard/CourseCard';
Please remove this.

2023-02-26 11:24 UTC, stepan-lagunovsky commented on src/components/CreateCourse/CreateCourse.tsx
> +	const [authors, addAuthor] = useState(MOCKED_AUTHORS_LIST);
Please start with a comment at `RootComponent` about `models.ts`
And update this two hooks with interfaces.

2023-02-26 11:24 UTC, stepan-lagunovsky commented on src/components/Root/RootComponent.tsx
> +
Please remove this empty line and update interface for authors state with IAuthor interface.
Please read a comment below

2023-02-26 11:24 UTC, stepan-lagunovsky commented on src/components/CreateCourse/CreateCourse.tsx
> +	const onValidateFunc = (value, name) => {
Please update params for `onInputChange` `onValidateFunc`.

2023-02-26 18:29 UTC, YauheniyaSeviarynets commented on src/components/Root/RootComponent.tsx
> +
Done

2023-02-26 18:32 UTC, stepan-lagunovsky approved these changes

2023-02-26 18:33 UTC, YauheniyaSeviarynets approved these changes

2023-02-26 18:35 UTC, YauheniyaSeviarynets approved these changes

2023-02-26 18:36 UTC, stepan-lagunovsky requested changes

2023-02-26 18:36 UTC, stepan-lagunovsky commented on src/components/Courses/Courses.tsx
> +import { CourseCard } from './components/CourseCard/CourseCard';
Remove empty lines please. Keep only between lib/imports

2023-02-26 18:36 UTC, stepan-lagunovsky approved these changes

2023-02-26 18:40 UTC, stepan-lagunovsky approved these changes

2023-02-26 18:43 UTC, stepan-lagunovsky approved these changes

2023-02-26 18:48 UTC, stepan-lagunovsky approved these changes

2023-02-26 18:48 UTC, YauheniyaSeviarynets approved these changes

2023-02-27 09:42 UTC, stepan-lagunovsky requested changes

2023-02-27 09:42 UTC, stepan-lagunovsky commented on src/components/Root/RootComponent.tsx
> +import App from 'src/App';
It's a bit tricky to investigate components with such mixed import order and spacing between each group of imports. Yes - it's better to separate each group of imports but when it's not too much:
```
import React, { FC } from 'react';
import { useNavigate, Navigate, useParams } from 'react-router-dom';

import { IPaths } from 'src/constants';

import { Button } from 'src/common/Button/Button';

import {
	getCourseAuthor,
	getCourseDuration,
	getCreationDate,
} from '../../helpers';

import { ICourse, IAuthor } from '../../models';

import styles from './CourseInfo.module.css';
```

You can choose one approach, let's say something like this:
```
1    // libs
2    //....
3
4     //interfaces
5     // constants
..      // helpers
..      // components

20... // css
```

And organize imports like this:
```
import React, { FC } from 'react';
import { useNavigate, Navigate, useParams } from 'react-router-dom';

import { ICourse, IAuthor } from '../../models';
import { IPaths } from 'src/constants';
import {
	getCourseAuthor,
	getCourseDuration,
	getCreationDate,
} from '../../helpers';
import { Button } from 'src/common/Button/Button';

import styles from './CourseInfo.module.css';
```
Later you can even add rules to your eslint config to automaticaly lint import order.

But for now - please check each file in `src`dir and update import order the same consistent way each file.

2023-02-27 09:42 UTC, stepan-lagunovsky commented on src/components/Root/RootComponent.tsx
> +	const [courses, updateCourse] = useState(MOCKED_COURSES_LIST);
Please add empty line here

2023-02-27 09:42 UTC, stepan-lagunovsky commented on src/components/Root/RootComponent.tsx
> +
But here remove.
And we will group these two hook groups this way as well

2023-02-27 09:42 UTC, stepan-lagunovsky commented on src/helpers/getCourseDuration.ts
> +	const hours = Math.trunc(mins / 60);
Please add type here:
`const getCourseDuration = (mins) => {`

2023-02-27 09:42 UTC, stepan-lagunovsky commented on src/helpers/getCreationDate.ts
> +export const getCreationDate = (date) => {
And param type here

2023-02-27 09:42 UTC, stepan-lagunovsky commented on src/components/Root/RootComponent.tsx
> +		setUser((prev) => ({
Not really important - but maybe `prevState` will be better for readability

2023-02-27 11:13 UTC, stepan-lagunovsky requested changes

2023-02-27 11:13 UTC, stepan-lagunovsky commented on src/components/Header/Header.tsx
> +				<div className={styles.authInfo}>
Here we have to implement two points:

1) Remove user's name for the Login and Registration pages
2) Remove Logout button from header for the Logon and Registration pages
So we need to improve somehow our ternary operator to hide button and username for authRoutes.

So lets say we have an array of two lets say authRoutes = [IPaths.Login, IPaths.Registration]

We have two options.
A) Simply check if this array includes our pathname and using this variable - improve our ternary operator when we show button and userName.

B) Or we have a special hook in react-router-dom v6 - `matchPath`
So using this hook you can check if .some() paths in such array matchPath(...) to calculate are we on auth routes.
And using this variable - improve our ternary operator when we show button and userName.

2023-02-27 13:01 UTC, ekseverinets commented on src/helpers/getCourseDuration.ts
> +	const hours = Math.trunc(mins / 60);
Added

2023-02-27 13:02 UTC, ekseverinets commented on src/components/Root/RootComponent.tsx
> +	const [courses, updateCourse] = useState(MOCKED_COURSES_LIST);
Added a line

2023-02-27 22:17 UTC, stepan-lagunovsky approved these changes

2023-02-27 23:37 UTC, merged